### ISSUE TITLE
missing script: develop

### ISSUE THREAD

**Issue by smth** [okfn/spend-publishing-dashboard#78]
I just tried running this locally, following the readme. I got the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node5/5.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'develop' ]
2 info using npm@3.8.6
3 info using node@v5.11.1
4 verbose stack Error: missing script: develop
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:147:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:57:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd /Users/sam/www/okfn/data-quality-dashboard
6 error Darwin 15.6.0
7 error argv "/usr/local/Cellar/node5/5.11.1/bin/node" "/usr/local/bin/npm" "run" "develop"
8 error node v5.11.1
9 error npm  v3.8.6
10 error missing script: develop
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by pwalsh** [comment]
@smth there is no develop command in this codebase. Try `npm run start`

**Comment by georgiana-b** [comment]
@smth As Paul mentioned, the setup is complete after `npm install` and you can run `npm run start` directly. However,  make sure to run `npm run build` after changes in UI.

**Comment by smth** [comment]
OK, thanks (the readme needs correcting ;)
